services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: globant_db
      MYSQL_USER: sebastianBonilla
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: globant_db
      DB_USER: sebastianBonilla
      DB_PASS: root

volumes:
  mysql_data:
